### ISSUE TITLE
Fix Number of Digits Displayed

### ISSUE THREAD

**Issue by TJohns03** [USEPA/power-profiler#6]
NYCW SO2 emission rate is 0.016, but with the power profiler rounding, it is displayed as 0.0, and no SO2 emissions are calculated.

**Comment by j-tafoya** [comment]
This happens in the preparation script. It rounds the values to the tenths place. What should it be rounded to?

**Comment by maheese** [comment]
SO2 Rate should be rounded to the hundredths (0.00) place.  Leave other values the same (tenths place)

**Comment by ibarra-michelle** [comment]
The NYCW subregion SO2 0.0 number comes from the subregion.json file. I updated the subregion.json to reflect 0.016 for NYCW. As a future step, we should consider updating how the subregion.json file is generated so that the SO2 Rate is rounded to the hundredths (0.00) place.

**Comment by ibarra-michelle** [comment]
In the prep folder, the README.md step #7 says to run the command to add the states.json file. However, the add_states.js file line #4 is is looking for a states.json file to read.
![add_states js-screenshot](https://user-images.githubusercontent.com/20859753/116621998-fe3ed180-a911-11eb-940c-13f5a7318d0b.png)
