### ISSUE TITLE
Address accessibility issues with renewable/non-renewable map

### ISSUE THREAD

**Issue by maheese** [USEPA/power-profiler#68]
The renewable/non-renewable map is not color blind friendly (the gradient goes from green to red).  Adjust the color/gradient so it is accessible.  This can be done by either using one color gradient or choosing multiple colors from a color blind friendly palette.

**Comment by maheese** [comment]
@TJohns03 how is this for a colorblind friendly color scheme?

![image](https://user-images.githubusercontent.com/16920772/123841614-c2a69080-d8dd-11eb-9a7f-a162010346f8.png)

**Comment by TJohns03** [comment]
I think that looks good.
